PR for frontend
DBL-App-development-2023-G7/musicmap pull request #17
Opened 2023-03-15 15:28 UTC by CodeNamedRobin

2023-03-16 15:08 UTC, Pradyuman7 commented on app/src/main/res/drawable/round_rect.xml
> +        android:color="#262626"/>
Is this going to be a color that we use at various places in our app? Then we should probably store it in colors.xml

2023-03-16 15:08 UTC, Pradyuman7 commented on app/src/main/res/values-land/dimens.xml
Why do we have multiple values directories, and with their own dimens.xml?

2023-03-17 09:53 UTC, TPGamesNL requested changes

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
![image](https://user-images.githubusercontent.com/29547183/225864455-b4da62c5-e01e-4b3e-aca8-073c2978efe1.png)
![image](https://user-images.githubusercontent.com/29547183/225865203-cf10e6eb-96f7-4db8-88a2-24cafb703b92.png)

like we saw during the meeting

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
When I rotate the screen, the EditTexts get cleared (e.g. I enter email, rotate screen, then email is gone)

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
It also goes to back to the login screen when you're on the register screen and rotate the phone

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_height="match_parent">
IDE gives a warning about this line (don't listen to its suggested fix, it gives infinite scroll)

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
> +                android:text="Music \nMap"
Hardcoded string

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_register.xml
> +                android:text="MusicMap"
Hardcoded string

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
> +                android:textSize="90dp"
Use sp for text size, not dp

2023-03-17 09:53 UTC, TPGamesNL commented on app/build.gradle
> +        viewBinding true
What do we need this for?

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_register.xml
![image](https://user-images.githubusercontent.com/29547183/225870383-4d292431-9aeb-4031-9074-14bad398f143.png)
these should be aligned

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_register.xml
check with tablet:
![image](https://user-images.githubusercontent.com/29547183/225870676-b9f53131-96d7-4398-ad35-f1517083fb90.png)

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_register.xml
Same for buttons on login fragment

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/values-w600dp/dimens.xml
> +    <dimen name="fab_margin">48dp</dimen>
I don't see the `fab_margin` dimension used anywhere

2023-03-17 09:53 UTC, TPGamesNL commented on app/src/main/res/layout/fragment_login.xml
> +            <androidx.constraintlayout.widget.ConstraintLayout
Is it fine to just use a ConstraintLayout inside of a ConstraintLayout?

2023-03-17 10:23 UTC, TPGamesNL commented
Btw there are build errors with the fonts, because both master and your branch added the same font

2023-03-19 11:04 UTC, CodeNamedRobin commented on app/src/main/res/drawable/round_rect.xml
> +        android:color="#262626"/>
This is not a color that's going to be used a lot I believe, but I can add it anyways.

2023-03-19 12:00 UTC, CodeNamedRobin commented on app/build.gradle
> +        viewBinding true
No clue why that was added, removed.

2023-03-26 18:53 UTC, TPGamesNL commented on app/src/main/java/com/example/musicmap/screens/auth/AuthActivity.java
> +        System.out.println("Created activity.");
If this is a debug message for testing, remove it. If it should be kept, use Log.d/i/w/e instead

2023-03-26 18:53 UTC, TPGamesNL commented on app/src/main/res/layout-land/fragment_register.xml
![image](https://user-images.githubusercontent.com/29547183/227797350-5505bed0-1a1d-4971-b95d-5eff871896e5.png)
I think the back and register buttons should be on the same horizontal line

2023-03-27 14:51 UTC, TPGamesNL approved these changes

2023-03-27 14:51 UTC, merged