MusicMemoryScreen
DBL-App-development-2023-G7/musicmap pull request #72
Opened 2023-04-05 14:50 UTC by CodeNamedRobin

Pull request for the screen that shows Music Memories yay.

2023-04-05 19:33 UTC, TPGamesNL approved these changes
Can be merged when merge conflicts are resolved 👍

2023-04-06 07:12 UTC, Pradyuman7 requested changes

2023-04-06 07:12 UTC, Pradyuman7 commented on app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
> +        HomeActivity homeActivity = (HomeActivity) activityContext;
We should not use context this way now that the feed adapter is also being used in the ProfileActivity for showing music memories of a user.

This would probably crash our app

2023-04-06 11:35 UTC, TPGamesNL commented on app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
> +        HomeActivity homeActivity = (HomeActivity) activityContext;
Crashes indeed, stack trace: https://pastebin.com/TkxGcCe1

2023-04-06 11:53 UTC, CodeNamedRobin commented on app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
> +        HomeActivity homeActivity = (HomeActivity) activityContext;
@Pradyuman7, you added this? How would you fix it?

2023-04-06 11:54 UTC, Pradyuman7 commented on app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
> +        HomeActivity homeActivity = (HomeActivity) activityContext;
Yes, but now that we have the FeedAdapter being used in ProfileActivity as well, this won't work. I think Teun is working on a fix atm

2023-04-06 11:55 UTC, TPGamesNL commented on app/src/main/java/com/example/musicmap/feed/FeedAdapter.java
> +        HomeActivity homeActivity = (HomeActivity) activityContext;
I'm trying rn yes

2023-04-06 12:16 UTC, andreitudorp requested changes
Crash when going back from the music memory fragment
https://pastebin.com/2qz6bsMf

2023-04-06 12:40 UTC, andreitudorp approved these changes
LGTM!

2023-04-06 12:51 UTC, TPGamesNL approved these changes

2023-04-06 12:54 UTC, andreitudorp approved these changes

2023-04-06 13:11 UTC, merged